services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    env_file:
      - .env
    container_name: codica
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
